### PR TITLE
Support final dot for DNS names

### PR DESCRIPTION
**Pull request by danog**

### CODE REVIEW

**Comment by danog** [comment]
ping

**Comment by kelunik** [comment]
Thanks, merged. GitHub somehow hung, so it doesn't reflect the PR as merged correcty, but it is merged.

We're in the process of deprecating and removing `amphp/uri` from all our libraries in favor of the league URI parser libary. We'll need to apply this PR to `amphp/dns` as well. Do you want to do that?

**Comment by danog** [comment]
Well I personally have no issue with using pre-existing libraries such as the league URI libraries, as long as the switch is done in all amphp libraries.
I'd gladly make a PR to update the composer.json of amphp/dns (if that's what you meant), but I guess a release would have to be tagged, first.

**Comment by kelunik** [comment]
@danog The switch will be done, but not immediately. The major issue is that `parse_url` has some known quirks.

There's no need to change the DNS `composer.json`, we just need to change the normalization function there, which has been moved there from this package.

https://github.com/amphp/dns/blob/cb65162596293e0580acccf2d97d3eeb751235fd/lib/functions.php#L85

**Comment by danog** [comment]
Oh ok right, pr incoming

**Comment by danog** [comment]
Would you mind making a release btw, I'm still relying on this lib in my project :)

**Comment by kelunik** [comment]
@danog Done. :-)

**Comment by danog** [comment]
Thanks.

**Pull request closed without merging**
